language: php
php:
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover clover.xml --bootstrap ./tests/bootstrap.php ./tests/

after_script:
  - if [[ "`php --version`" != *HipHop* ]] ; then php vendor/bin/coveralls -v ; fi
  - if [[ "`php --version`" != *HipHop* ]] ; then php vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml ; fi
