language: php
php:
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit

after_script:
  - if [[ "`php --version`" != *HipHop* ]] ; then CODECLIMATE_REPO_TOKEN=a69c871494bb9454a988a63745d378cfc632739d0e47b7b4aefd6cf94bc5dff2 ./vendor/bin/test-reporter

