language: php
php:
  - 5.5
  - 5.6
  - 7.0

addons:
  code_climate:
    repo_token:a69c871494bb9454a988a63745d378cfc632739d0e47b7b4aefd6cf94bc5dff2

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/test-reporter

